daemon: true
iAgreeNotToBeStupid: true
log:
    activityFilePath: "/opt/dvm/log/control-activity/"
    disableNonAuthoritiveLogging: false
    displayLevel: 1
    fileLevel: 1
    filePath: "/opt/dvm/log/control/"
    fileRoot: cc
    useSyslog: false
network:
    address: 10.0.40.194
    allowActivityTransfer: true
    allowDiagnosticTransfer: true
    allowStatusTransfer: true
    debug: false
    enable: true
    encrypted: true
    id: 10000
    packetDump: false
    password: RPT1234
    port: 62031
    presharedKey: 000102030405060708090A0B0C0D0E0F000102030405060708090A0B0C0D0E0F
    restAddress: 127.0.0.1
    restDebug: false
    restEnable: true
    restPassword: PASSWORD
    restPort: 9991
    restSsl: false
    restSslCertificate: web.crt
    restSslKey: web.key
    rpcAddress: 127.0.0.1
    rpcDebug: false
    rpcPassword: "ULTRA-VERY-SECURE-DEFAULT"
    rpcPort: 9891
    saveLookups: true
    updateLookups: true
protocols:
    dmr:
        enable: false
    nxdn:
        enable: false
    p25:
        allowExplicitSourceId: false
        callHang: 5
        control:
            ackRequests: true
            broadcast: true
            dedicated: true
            disableAdjSiteBroadcast: false
            disableGrantSourceIdCheck: false
            disableTSDUMBF: false
            duration: 1
            enable: true
            enableTimeDateAnn: false
            explicitTDUGrantRelease: true
            interval: 300
            notifyActiveTG: false
            redundantGrantTransmit: false
            redundantImmediate: true
        controlOnly: true
        convNetGrantDemand: false
        debug: false
        demandUnitRegForRefusedAff: true
        disableDenyResponse: false
        disableNetworkGrant: false
        disableNetworkHDU: false
        disableUnitRegTimeout: false
        dumpDataPacket: false
        dumpTsbkData: false
        enable: true
        forceAllowTG0: false
        frameLossThreshold: 6
        ignoreAffiliationCheck: false
        ignoreDataCRC: false
        immediateCallTerm: true
        inhibitUnauthorized: false
        legacyGroupGrnt: true
        legacyGroupReg: false
        noMessageAck: true
        noStatusAck: false
        queueSize: 12
        repeatDataPacket: true
        requireLLAForReg: false
        silenceThreshold: 124
        sndcpSupport: false
        tduPreambleCount: 6
        unitToUnitAvailCheck: false
        verbose: true
        verifyAff: false
        verifyReg: false
system:
    activeTickDelay: 5
    config:
        announcementGroup: FFFE
        authoritative: true
        channelId: 2
        channelNo: 120
        #controlCh:
        #    notifyEnable: false
        #    presence: 120
        #    rpcAddress: 127.0.0.1
        #    rpcPassword: "ULTRA-VERY-SECURE-DEFAULT"
        #    rpcPort: 9891
        defaultNetIdleTalkgroup: 0
        nac: 293
        netId: BB800
        pSuperGroup: FFFE
        rfssId: 1
        secure:
            key: 000102030405060708090A0B0C0D0E0F
        siteId: 1
        supervisor: true
        sysId: 001
        #voiceChNo:
        #    - channelId: 2
        #      channelNo: 8c0
        #      rpcAddress: 127.0.0.1
        #      rpcPassword: "ULTRA-VERY-SECURE-DEFAULT"
        #      rpcPort: 9892
    cwId:
        callsign: ABCD123
        enable: false
        time: 15
    disableWatchdogOverflow: false
    duplex: true
    fixedMode: false
    iden_table:
        file: /opt/dvm/rules/iden_table.dat
        time: 30
    identity: "W25-CC"
    idleTickDelay: 5
    info:
        height: 1
        latitude: "-83.689428"
        location: "Repeater Site, Antarctica"
        longitude: "-39.194973"
        power: 10
    localTimeOffset: 0
    modeHang: 10
    modem:
        cosLockout: false
        dcBlocker: true
        debug: false
        dfsi:
            callTimeout: 200
            dfsiTIAMode: false
            fsc: false
            fscHeartbeat: 5
            fullDuplex: true
            initiator: false
            jitter: 200
            rtrt: true
        disableOFlowReset: false
        displayModemDebugMessages: false
        dmrFifoLength: 560
        dmrRxDelay: 7
        dumpModemStatus: false
        fdmaPreamble: 80
        hotspot:
            adfGainMode: 2
            afcEnable: true
            afcKI: 13
            afcKP: 5
            afcRange: 1
            dmrDiscBWAdj: 0
            dmrPostBWAdj: 0
            nxdnDiscBWAdj: 0
            nxdnPostBWAdj: 0
            p25DiscBWAdj: 0
            p25PostBWAdj: 0
            rxTuning: "-128"
            txTuning: "-128"
        ignoreModemConfigArea: false
        nxdnFifoLength: 538
        nxdnFifoLenth: 538
        p25CorrCount: 2
        p25FifoLength: 522
        packetPlayoutTime: 10
        protocol:
            mode: air
            type: uart
            uart:
                port: /dev/ttyUSB1
                speed: 115200
        pttInvert: false
        repeater:
            dmrSymLvl1Adj: 0
            dmrSymLvl3Adj: 0
            nxdnDiscBWAdj: 0
            nxdnPostBWAdj: 0
            nxdnSymLvl1Adj: 0
            nxdnSymLvl3Adj: 0
            p25SymLvl1Adj: 0
            p25SymLvl3Adj: 0
        rssiMappingFile: RSSI.dat
        rxDCOffset: 0
        rxInvert: false
        rxLevel: 50
        softpot:
            rssiCoarse: 127
            rssiFine: 127
            rxCoarse: 127
            rxFine: 127
            txCoarse: 127
            txFine: 127
        trace: false
        txDCOffset: 0
        txInvert: false
        txLevel: 50
    radio_id:
        acl: false
        file: /opt/dvm/rules/rid_acl.dat
        time: 2
    rfTalkgroupHang: 10
    simplexSameFrequency: false
    talkgroup_id:
        acl: false
        file: /opt/dvm/rules/talkgroup_rules.yml
        time: 2
    timeout: 180
